[build]
  publish = "public"
  command = """
    # Install JupyterLite and dependencies
    pip install jupyterlite &&
    
    # Install additional dependencies for R kernel (if not bundled in the JupyterLite package)
#    pip install jupyterlite-kernel-r &&
#     pip install jupyterlab-kernel-r &&

    # Build the Hugo site
    hugo --minify --gc &&
    
    # Add the R kernel to the JupyterLite environment
#    jupyter lite add --kernel r &&
    
    # Build the JupyterLite environment
    jupyter lite build --output-dir public/live
  """

[build.environment]
  HUGO_VERSION = "0.109.0"
  HUGO_BASEURL = "/"
  PYTHON_VERSION = "3.11"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
